// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/component/navbar/navbar";
// import Footer from "@/component/footer/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "AQT",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Navbar/>
//          <main className="pt-[125px]">
//         {children}
//         </main>
//         <Footer/>
//       </body>
//     </html>
//   );
// }



// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/navbar";
import Footer from "@/component/footer/footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = "https://www.atlantaquantumtech.com";

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Atlanta Quantum Tech",
    template: "%s | Atlanta Quantum Tech",
  },
  description:
    "Atlanta Quantum Tech is a global IT solutions company delivering AI, cloud, and digital transformation services to enterprises worldwide.",
  openGraph: {
    type: "website",
    siteName: "Atlanta Quantum Tech",
    url: SITE_URL,
    images: [
      {
        url: "/og/default-og.jpg",
        width: 1200,
        height: 630,
        alt: "Atlanta Quantum Tech",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@atlquantumtech",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Atlanta Quantum Tech",
    url: SITE_URL,
    potentialAction: {
      "@type": "SearchAction",
      target: `${SITE_URL}/search?q={search_term_string}`,
      "query-input": "required name=search_term_string",
    },
    publisher: {
      "@type": "Organization",
      name: "Atlanta Quantum Tech Pvt Ltd",
      logo: {
        "@type": "ImageObject",
        url: `${SITE_URL}/logo.png`,
      },
    },
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Global Schema */}
        <Script
          id="website-schema"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />

        <Navbar />
        <main className="pt-[125px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
